AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template for Network Only


Mappings:
  Data:
    values:
      wfoVPC: "vpc-0e9ef5cafc82aa5e8"
      wfoAccount: "692416605838"
      wfoCIDR: "10.233.0.0/18"
      Owner: 'Network Teams'

# the role has to be requested from enterprise team

Resources:
  VPCPeeringConnectionCore:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue 'CoreNetwork-Vpc'
      PeerVpcId: !FindInMap [ Data,values,wfoVPC ]
      PeerOwnerId: !FindInMap [ Data,values,wfoAccount ]
      PeerRegion: !Ref AWS::Region
      PeerRoleArn: arn:aws:iam::692416605838:role/ap-northeast-3-accept-peering-role

  VPCPeeringConnectionVoice1:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue 'VoiceNetwork-Vpc'
      PeerVpcId: !FindInMap [ Data,values,wfoVPC ]
      PeerOwnerId: !FindInMap [ Data,values,wfoAccount ]
      PeerRegion: !Ref AWS::Region
      PeerRoleArn: arn:aws:iam::692416605838:role/ap-northeast-3-accept-peering-role

  VPCPeeringConnectionVoice2:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue 'VoiceNetwork2-Vpc'
      PeerVpcId: !FindInMap [ Data,values,wfoVPC ]
      PeerOwnerId: !FindInMap [ Data,values,wfoAccount ]
      PeerRegion: !Ref AWS::Region
      PeerRoleArn: arn:aws:iam::692416605838:role/ap-northeast-3-accept-peering-role


  VPCPeeringRouteCore1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az1CoreRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az1LambdaRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore3:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az1UntrustRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore4:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az1VIPRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore5:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az2CoreRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore6:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az2LambdaRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore7:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az2UntrustRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore8:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-Az2VIPRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteCore9:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'CoreNetwork-ManagementRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionCore

  VPCPeeringRouteVoice1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'Voice-Az1TrustRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionVoice1

  VPCPeeringRouteVoice2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue 'Voice-VPC2Az2TrustRouteTable'
      DestinationCidrBlock: !FindInMap [ Data,values,wfoCIDR ]
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionVoice2

Outputs:
  VPCPeeringConnectionIdCore:
    Value: !Ref VPCPeeringConnectionCore

  VPCPeeringConnectionIdVoice1:
    Value: !Ref VPCPeeringConnectionVoice1

  VPCPeeringConnectionIdVoice2:
    Value: !Ref VPCPeeringConnectionVoice2


