maintainers:
  - name: systems-engineering
    email: systemengineering@nice.com
  - name: kubernetes-admins
    email: devops-cloud-native-core@niceincontact.com

integrations:
  aws: omilia-frm-na2

runner_image: "369498121101.dkr.ecr.us-west-2.amazonaws.com/cnc/spacelift-runner:1.9"
worker_pool_name: omilia-ec2-frm
terraform_version: 1.6.2
auto_deploy: false
remove_default_after_plan: true
remove_execute_only_selected_commands: true
branch: omilia-demo-fedramp

contexts:
  cxossp-github-personal-access-token: 0

before_init:
  - "cat /mnt/workspace/github.netrc >> ~/.netrc"
  - "chmod 600 ~/.netrc"
after_plan:
  - "tflint --init"
  - "tflint; if [ $? -eq 0 ]; then echo -e \"No tflint error(s) found.\\n\"; else printf \"${RED}ERROR: tflint found the failures listed above!${NC}\\n\"; val_errors=2; fi"
