AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for creating SonusProvisioning base NLB
Parameters:
  CertificateARN:
    Description: >-
      The ARN of the SSL certificate created in this account and region (e.g.
      arn:aws:acm:us-west-2:545209810301:certificate/8a3d4b9e-5aa0-46fd-8381-0d1ab83b9621)
    Type: String
    Default: 'arn:aws:acm:eu-central-1:533267422300:certificate/38e5f776-f475-4f46-a114-0a0517d4ff3b'
Resources:
  SonusProvisioning:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: true
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue GlobalSecurityGroups-SonusNLBSecurityGroup
      Type: network
      Name: Sonus-provisioning
      Subnets:
        - !ImportValue DMZNetwork-Az13rdPartyDMZSubnet
        - !ImportValue DMZNetwork-Az23rdPartyDMZSubnet
      Tags:
        - Key: InfrastructureOwner
          Value: Network Teams
        - Key: DeviceType
          Value: Network Load Balancer
        - Key: Cluster
          Value: Global
        - Key: Product
          Value: Billing
        - Key: ApplicationOwner
          Value: Voice Engineering
  SonusProvisioningTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /emsapi/services/PSXAPI/r16_01_00
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Port: 443
      Protocol: TLS
      Tags:
        - Key: Name
          Value: SonusProvisioningTG
      TargetType: ip
      Targets:
        - AvailabilityZone: all
          Id: '10.8.10.180'     ##s1fr8rbrmp01 Data Center RAMP Server IP
          Port: 443
        - AvailabilityZone: all
          Id: '10.8.26.180'     ##s1mu4rbrmp01 Data Center RAMP Server IP
          Port: 443
      VpcId: !ImportValue DMZNetwork-Vpc
      Name: SonusProvisioningTG
  SonusProvisioningListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref 'SonusProvisioningTG'
      LoadBalancerArn: !Ref 'SonusProvisioning'
      Port: 443
      Protocol: TLS
      Certificates:
        - CertificateArn: !Ref CertificateARN
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
  sonusemsDNS:
    Type: 'AWS::Route53::RecordSet'
    #Condition: CreateDNSRecords
    Properties:
      HostedZoneName: !Join
        - ''
        - - !ImportValue RegionConfig-ExternalDomainName-NiceCxoneDomain
      Name: !Join
        - ''
        - - sonusems
          - .
          - !ImportValue RegionConfig-ExternalDomainName-NiceCxoneDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt
          - SonusProvisioning
          - DNSName
        HostedZoneId: !GetAtt
          - SonusProvisioning
          - CanonicalHostedZoneID