AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS WAFv2 blocking specific countries with SQLi protection"

Parameters:
  WebACLName:
    Type: String
    Default: "CommonICProdSouthAfricaNICWebACL"
    Description: "Name of the WAF WebACL"

  BlockedCountries:
    Type: CommaDelimitedList
    Description: "List of 2-letter country codes to block"
    Default: "BD,CU,IR,KP,RU,SY,PS"

Mappings:
  TagIds:
    values:
      Product: 'Network'
      DeviceType: 'Network Security Group'
      InfrastructureOwner: 'Network Teams'
      ApplicationOwner: 'Network Teams'

Resources:
  # WAFv2 Web ACL
  CommonNICWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Ref WebACLName
      Scope: REGIONAL
      Description: "This is Web ACL for Cluster ALB managed by Network Teams"
      Tags:
        - Key: DeviceType
          Value: !FindInMap [ TagIds , values, DeviceType ]
        - Key: InfrastructureOwner
          Value: !FindInMap [ TagIds , values, InfrastructureOwner ]
        - Key: ApplicationOwner
          Value: !FindInMap [ TagIds , values, ApplicationOwner ]
        - Key: Product
          Value: !FindInMap [ TagIds , values, Product ]
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Ref WebACLName
        SampledRequestsEnabled: true
      Rules:
        # 1. SQL Injection Rule (Priority 0)
        - Name: AWS-AWSManagedRulesSQLiRuleSet
          Priority: 0
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
              RuleActionOverrides:
                - Name: SQLi_QUERYARGUMENTS
                  ActionToUse:
                    Count: {}
                - Name: SQLi_BODY
                  ActionToUse:
                    Count: {}
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "AWS-AWSManagedRulesSQLiRuleSet"

        # 2. Country Blacklist Rule (Priority 1)
        - Name: CountryBlackList
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "CountryBlackList"
          Statement:
            GeoMatchStatement:
              CountryCodes: !Ref BlockedCountries

Outputs:
  CommonNICWAFWebACLArn:
    Description: "ARN of the WAF WebACL"
    Value: !GetAtt CommonNICWebACL.Arn
    Export:
      Name: !Ref WebACLName