terraform {
  required_version = ">= 1.3.7"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0.0, < 6.0.0"
    }
  }
}

provider "aws" {
  region = "me-central-1"
}

# This will cause tokens generated by the STS Global endpoint to be
# `Valid in all AWS Regions` rather than the default value of `AWS
# Regions enabled by default`. This is necessary because the `me-central-1`
# region is not enabled by default.
# For more info on this resource see:
# https://github.com/hashicorp/terraform-provider-aws/issues/31244
resource "aws_iam_security_token_service_preferences" "this" {
  global_endpoint_token_version = "v2Token"
}